### ISSUE TITLE
Oracle directory is case sensitive

### ISSUE THREAD

**Issue by jonheller1** [maxsatula/ocp#33]
The Oracle directory parameter must be in upper case or else the error "Failed to open an Oracle remote file for reading" is returned.  It would be helpful if the parameter was case-insensitive, since the Oracle objects are case insensitive.  Perhaps this only needs an `UPPER(...)` in a query.

**Comment by maxsatula** [comment]
There are 4 options to solve the issue.
1. Always convert a directory argument to uppercase as suggested in the issue description, a sort of `WHERE UPPER(:argument) = directory_name` clause. **Problem:** if someone creates a lowercase directory in the database using quotation marks (for instance, `CREATE DIRECTORY "lowercase_pump_dir" AS ...`), there will be no way to reference it from `ocp`.
2. Do case insensitive search of a directory in oracle, i.e. use something like `WHERE UPPER(:argument) = UPPER(directory_name) AND rownum = 1`. **Problem:** there is an ambiguity if multiple directories exist such as `my_dir`, `My_DiR`, and `MY_DIR`. And there would be no way to specify which one is actually needed.
3. Do an Oracle SQL way: if a directory specified in quotation marks (for example, `ocp /@mydb "my_dir":myfile.dmp myfile.dmp`), then use as is, otherwise treat it as uppercase. This makes command line syntax a little bit more complicated, but it should cover all cases.
4. Do not "fix" anything. Force end user to specify directory names with an appropriate case.

**Comment by maxsatula** [comment]
Option 5 looks the most attractive.
- [ ] If case-sensitive search failed but case-insensitive search succeeded, write a warning message to stderr.
