### ISSUE TITLE
Windows build missing MSVCR120.dll

### ISSUE THREAD

**Issue by jonheller1** [maxsatula/ocp#34]
When I tried to run the .exe I got the error message "The program can't start because MSVCR120.dll is missing from your computer.  Try reinstalling the program to fix this problem."  I resolved the problem by downloading and installing vcredist-x86 as described in this post: http://superuser.com/questions/827752/run-vcredist-x86-exe-missing-msvcr120-dll

It might also help to explain that the Oracle thin client needs to be unzipped in the same directory as OCP.  Or perhaps even add those to the distribution if there's no license issues.

**Comment by maxsatula** [comment]
Of course. Forgot to mention, since a Windows binary has been built with Microsoft Visual Studio 2003, that is expected that **Visual C++ Redistributable Packages for Visual Studio 2013** is a dependency. 

TODO:
- [ ] document a dependency somewhere (perhaps to `win/README.md`)
- [ ] find a way to get rid of that dependency, if any (linker option?)

Oracle Client does not have to be in the same directory as `ocp`. Adding of Oracle Client location to `PATH` will help too. That does not even have to be a system setting; a session-wide adjustment of `PATH` variable in a single command line window should work:
```
cmd
path %PATH%;c:\instantclient_11_2
ocp ...
```
I thought it was an obvious requirement, since that is a general rule to add an Oracle Client to `PATH` variable. If that is not that obvious as believed, I will add it to `win/README.md` too.

**Comment by maxsatula** [comment]
- [ ] try to compile with Visual C++ 2005 Express Edition http://go.microsoft.com/fwlink/?linkid=57034

**Comment by maxsatula** [comment]
No success with either Visual C++ 2005 or link options. Updated documentation with a requirement.
